/*!
 * Copyright (c) 2020 Digital Bazaar, Inc. All rights reserved.
 */
import { describe, it, expect } from 'vitest'
import type {
  IOkpPublicJwk,
  IOkpSecretJwk
} from '@interop/data-integrity-core'
import { Ed25519VerificationKey } from '../../src/index.js'
import * as jose from 'jose'

describe('compatibility', () => {
  describe('jose lib roundtrip import/export', () => {
    it('should round-trip to and from jose', async () => {
      // generated by 'jose' lib via `await jose.exportJWK(await jose.generateKeyPair('EdDSA'))`
      const exampleJoseSecretKey: IOkpSecretJwk = {
        kty: 'OKP',
        crv: 'Ed25519',
        x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
        d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI'
      }
      const exampleJosePublicKey: IOkpPublicJwk = {
        kty: 'OKP',
        crv: 'Ed25519',
        x: exampleJoseSecretKey.x
      }

      const keyPair = await Ed25519VerificationKey.fromJsonWebKey({
        type: 'JsonWebKey',
        publicKeyJwk: exampleJosePublicKey,
        secretKeyJwk: exampleJoseSecretKey
      })

      const exportedJwk: any = await keyPair.toJwk({
        publicKey: true,
        privateKey: true
      })

      expect(exportedJwk).toEqual({
        crv: 'Ed25519',
        d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI',
        x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
        kty: 'OKP'
      })

      const importedJoseKey = await jose.importJWK(exportedJwk, 'EdDSA', {
        extractable: true
      })
      expect(await jose.exportJWK(importedJoseKey)).toEqual({
        crv: 'Ed25519',
        d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI',
        x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
        kty: 'OKP'
      })
    })
  })
})
